# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Mappings
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

# Minecraft & Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=1.20.1-47.4.23
loader_version_range=[47,)

## Mod Properties
mod_id=omegafe
mod_name=Omega Flashlight FE Batteries
mod_license=MIT
mod_version=1.0.0-1.20.1
mod_group_id=it.ratlab.omegafe

# Omega Flashlight (compile-only dependency, local jar in libs/)
omega_version_range=[0.7.6,)
